export * from './Navbar';
export * from './Hero';
export * from './About';
export * from './Experience';
export * from './Tech';
export * from './Works';
export * from './Feedbacks';
export * from './Contact';
export * from './StarsCanvas';
